### ISSUE TITLE
Missing region in config

### ISSUE THREAD

**Issue by jwulf** [SamVerschueren/aws-lambda-invoke#2]
I'm getting this error when invoking a Lambda function:

{ [ConfigError: Missing region in config]
  message: 'Missing region in config',
  code: 'ConfigError',
  time: Wed Aug 12 2015 22:08:35 GMT+1000 (AEST) }

Where do I configure this?

**Comment by SamVerschueren** [comment]
Hi

This indeed is undocumented. There are a number of possibilities. The one I like most is by using environment variables. Make sure AWS_REGION is set to the region you want. 

Another possibility is by updating the config of the AWS library.

``` javascript
AWS.config.update({
    region: 'us-west-1'
});
```

You can find more information regarding this in the documentation of Amazon over here http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html

**Comment by jwulf** [comment]
Cool, that did it, thanks!

I'm doing it like this:

```
var AWS = require('aws-sdk');

// Config AWS Client
AWS.config.update({
    accessKeyId: Config.aws.admin_access_key,
    secretAccessKey: Config.aws.admin_secret_access_key,
    region: Config.aws.aws_region
});

/**
 * Export AWS Services
 */

module.exports.lambda = require('aws-lambda-invoke')(AWS);
```

This is actually in JAWS, I've added it to the `model_aws.js`.

**Comment by SamVerschueren** [comment]
Hi @jwulf 

Please note that Amazon (and I aswell) are not really a fan of embedding AK/SK (access key/secret key) inside of the application as noted here http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Hard-Coding_Credentials.

> **Note**: We recommend you **not** hard-code credentials inside an application. Use this method only for small personal scripts or for testing purposes.

I prefer IAM roles or environment variables.

But maybe that is not really an option for JAWS?

**Comment by SamVerschueren** [comment]
Closing this as it is not really an issue.
